name: pulsa
description: "Aplikasi Penjualan Pulsa"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+24122701

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: 5.7.0
  either_dart: ^1.0.0
  equatable: 2.0.7
  flutter_svg: ^2.0.16
  gap: ^3.0.1
  get: 4.6.6
  get_it: 8.0.2
  google_fonts:
  heroicons_flutter: ^0.4.0
  hive: 2.2.3
  indonesia: ^2.0.0
  mask_text_input_formatter: ^2.9.0
  package_info_plus: 8.1.2
  path_provider: ^2.1.5
  pinput: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pretty_dio_logger: 1.4.0

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/provider/
    - assets/icons/
    - assets/backgrounds/