name: core
description: Core project getsurvey.
version: 0.0.1
homepage: www.getsurvey.id
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  advance_pdf_viewer_fork: "2.0.0"
  agora_rtc_engine: "6.3.2"
  amplitude_flutter: "3.16.4"
  another_flushbar: "1.12.30"
  audioplayers: "6.1.0"
  cached_network_image: "3.4.1"
  cropperx: "1.1.1"
  currency_text_input_formatter: "2.2.6"
  dartz: "0.10.1"
  data_connection_checker_nulls: "0.0.2"
  device_info_plus: "11.1.0"
  dio: "5.7.0"
  dotted_border: "2.1.0"
  dropdown_search: 5.0.6
  equatable: "2.0.5"
  expandable: "5.0.1"
  file_picker: "8.1.3"
  firebase_remote_config: "5.1.3"

  # remove
  #  flutter_app_version_checker: 0.3.2
  animations:
  bloc:
  another_carousel_pro:
  faker:
  flutter_bloc:
  firebase_crashlytics:
#  flutter_plugin_android_lifecycle: 2.0.23
  flutter_foreground_task: 8.13.0
#  flutter_callkit_incoming: "2.0.4+2"
  flutter_countdown_timer:
  flutter_exif_rotation: "0.5.2"
  flutter_inappwebview:
  flutter_local_notifications:
  firebase_messaging:
  flutter_rating_bar: "4.0.1"
  flutter_rating_stars:
  flutter_ringtone_player: "4.0.0+3"
  #  flutter_datetime_picker:
  flutter_datetime_picker_plus: 2.2.0
  flutter_spinkit: "5.2.1"
  flutter_switch:
  flutter_svg: "2.0.12"
  fluttertoast: "8.2.8"
  flutter_styled_toast: "2.2.1"
  gap: "3.0.1"
  geocoding:
  get: "4.6.6"
  get_it: "8.0.2"
  get_storage:
  google_fonts: "6.2.1"
  google_maps_flutter: ^2.9.0
  google_mlkit_text_recognition:
  http_mock_adapter:
  image_picker: "1.1.2"
  indonesia: "2.0.0"
  loader_overlay: 4.0.3
  location:
  mask_text_input_formatter: "2.9.0"
  nik_validator:
  package_info_plus: ^8.1.0
  permission_handler: "11.3.1"
  pinput: "5.0.0"
  photo_view: "0.15.0"
  pretty_dio_logger: "1.4.0"
  pull_to_refresh:
  open_store:
  rounded_expansion_tile:
  shared_preferences:
  shimmer: "3.0.0"
  slidable_button: "3.0.0+1"
  sliding_up_panel:
  socket_io_client: "3.0.1"
  timeline_tile:
  url_launcher: "6.3.1"

dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: 27fd339172572fe1b16cdcdae235b2a88f432e3c
      path: flutter_inappwebview_ios


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  assets:
    - .env
